// Copyright 2026 Block, Inc.

package parser_test

import (
	"testing"
)

// These statements are all valid MySQL that can appear in the binary log as
// Query events; spirit's pkg/change must be able to parse them.

func TestRepairTable(t *testing.T) {
	table := []testCase{
		{"REPAIR TABLE t1", true, "REPAIR TABLE `t1`"},
		{"repair tables t1, t2", true, "REPAIR TABLE `t1`, `t2`"},
		{"REPAIR NO_WRITE_TO_BINLOG TABLE t1 QUICK EXTENDED USE_FRM", true, "REPAIR NO_WRITE_TO_BINLOG TABLE `t1` QUICK EXTENDED USE_FRM"},
		{"REPAIR LOCAL TABLE t1 USE_FRM", true, "REPAIR NO_WRITE_TO_BINLOG TABLE `t1` USE_FRM"},
		{"REPAIR TABLE t1 EXTENDED QUICK", true, "REPAIR TABLE `t1` QUICK EXTENDED"},
		{"REPAIR TABLE", false, ""},
	}
	RunTest(t, table, false)
}

func TestRenameTables(t *testing.T) {
	table := []testCase{
		{"RENAME TABLES t1 TO t2", true, "RENAME TABLE `t1` TO `t2`"},
		{"RENAME TABLES t1 TO t2, t3 TO t4", true, "RENAME TABLE `t1` TO `t2`, `t3` TO `t4`"},
	}
	RunTest(t, table, false)
}

func TestAnalyzeTableHistograms(t *testing.T) {
	table := []testCase{
		{"ANALYZE TABLES t1, t2", true, "ANALYZE TABLE `t1`,`t2`"},
		{"ANALYZE TABLE t UPDATE HISTOGRAM ON c1, c2 WITH 8 BUCKETS", true, "ANALYZE TABLE `t` UPDATE HISTOGRAM ON `c1`,`c2` WITH 8 BUCKETS"},
		{"ANALYZE TABLE t UPDATE HISTOGRAM ON c WITH 4 BUCKETS AUTO UPDATE", true, "ANALYZE TABLE `t` UPDATE HISTOGRAM ON `c` WITH 4 BUCKETS AUTO UPDATE"},
		{"ANALYZE TABLE t UPDATE HISTOGRAM ON c AUTO UPDATE", true, "ANALYZE TABLE `t` UPDATE HISTOGRAM ON `c` AUTO UPDATE"},
		{"ANALYZE TABLE t UPDATE HISTOGRAM ON c MANUAL UPDATE", true, "ANALYZE TABLE `t` UPDATE HISTOGRAM ON `c` MANUAL UPDATE"},
		{`ANALYZE TABLE t UPDATE HISTOGRAM ON c USING DATA '{"histogram": {}}'`, true, "ANALYZE TABLE `t` UPDATE HISTOGRAM ON `c` USING DATA '{\"histogram\": {}}'"},
		{"ANALYZE TABLE t DROP HISTOGRAM ON c", true, "ANALYZE TABLE `t` DROP HISTOGRAM ON `c`"},
	}
	RunTest(t, table, false)
}

func TestTransactionSpellings(t *testing.T) {
	table := []testCase{
		{"BEGIN WORK", true, "START TRANSACTION"},
		{"COMMIT WORK", true, "COMMIT"},
		{"ROLLBACK WORK", true, "ROLLBACK"},
		{"COMMIT WORK AND CHAIN", true, "COMMIT AND CHAIN"},
		{"ROLLBACK WORK AND NO CHAIN NO RELEASE", true, "ROLLBACK"},
		{"ROLLBACK WORK TO SAVEPOINT sp1", true, "ROLLBACK TO sp1"},
		{"ROLLBACK WORK TO sp1", true, "ROLLBACK TO sp1"},
		{"START TRANSACTION READ ONLY, WITH CONSISTENT SNAPSHOT", true, "START TRANSACTION READ ONLY"},
		{"START TRANSACTION WITH CONSISTENT SNAPSHOT, READ WRITE", true, "START TRANSACTION"},
		{"START TRANSACTION WITH CONSISTENT SNAPSHOT, READ ONLY", true, "START TRANSACTION READ ONLY"},
	}
	RunTest(t, table, false)
}

func TestFlushOptions(t *testing.T) {
	table := []testCase{
		{"FLUSH USER_RESOURCES", true, "FLUSH USER_RESOURCES"},
		{"FLUSH OPTIMIZER_COSTS", true, "FLUSH OPTIMIZER_COSTS"},
		{"FLUSH LOCAL OPTIMIZER_COSTS", true, "FLUSH NO_WRITE_TO_BINLOG OPTIMIZER_COSTS"},
		{"FLUSH RELAY LOGS", true, "FLUSH RELAY LOGS"},
		{"FLUSH RELAY LOGS FOR CHANNEL 'group_replication_applier'", true, "FLUSH RELAY LOGS FOR CHANNEL 'group_replication_applier'"},
		{"FLUSH TABLES t1 FOR EXPORT", true, "FLUSH TABLES `t1` FOR EXPORT"},
		{"FLUSH TABLES t1, t2 WITH READ LOCK", true, "FLUSH TABLES `t1`, `t2` WITH READ LOCK"},
	}
	RunTest(t, table, false)
}

func TestAlterDatabaseReadOnly(t *testing.T) {
	table := []testCase{
		{"ALTER DATABASE d READ ONLY = 1", true, "ALTER DATABASE `d` READ ONLY = 1"},
		{"ALTER DATABASE d READ ONLY 0", true, "ALTER DATABASE `d` READ ONLY = 0"},
		{"ALTER DATABASE d READ ONLY = DEFAULT", true, "ALTER DATABASE `d` READ ONLY = DEFAULT"},
		{"ALTER DATABASE READ ONLY = 1", true, "ALTER DATABASE READ ONLY = 1"},
		{"ALTER SCHEMA d READ ONLY = 1 CHARACTER SET = utf8mb4", true, "ALTER DATABASE `d` READ ONLY = 1 CHARACTER SET = utf8mb4"},
	}
	RunTest(t, table, false)
}

func TestAlterView(t *testing.T) {
	table := []testCase{
		{"ALTER VIEW v AS SELECT * FROM t", true, "ALTER ALGORITHM = UNDEFINED DEFINER = CURRENT_USER SQL SECURITY DEFINER VIEW `v` AS SELECT * FROM `t`"},
		{"ALTER ALGORITHM = MERGE DEFINER = u@h SQL SECURITY INVOKER VIEW v (a, b) AS SELECT a, b FROM t WITH LOCAL CHECK OPTION", true, "ALTER ALGORITHM = MERGE DEFINER = `u`@`h` SQL SECURITY INVOKER VIEW `v` (`a`,`b`) AS SELECT `a`,`b` FROM `t` WITH LOCAL CHECK OPTION"},
		{"ALTER VIEW v AS", false, ""},
	}
	RunTest(t, table, false)
}

func TestXAStatements(t *testing.T) {
	table := []testCase{
		{"XA START 'gtrid'", true, "XA START 'gtrid'"},
		{"XA BEGIN 'gtrid'", true, "XA START 'gtrid'"},
		{"XA START 'g', 'b'", true, "XA START 'g', 'b'"},
		{"XA START 'g', 'b', 12", true, "XA START 'g', 'b', 12"},
		{"XA START X'41', X'42', 1", true, "XA START 'A', 'B', 1"},
		{"XA START 0x7465737462, 0x2030405060, 0xb", true, "XA START 'testb', ' 0@P`', 11"},
		{"XA START 'g' JOIN", true, "XA START 'g' JOIN"},
		{"XA START 'g' RESUME", true, "XA START 'g' RESUME"},
		{"XA END 'g'", true, "XA END 'g'"},
		{"XA END 'g' SUSPEND", true, "XA END 'g' SUSPEND"},
		{"XA END 'g' SUSPEND FOR MIGRATE", true, "XA END 'g' SUSPEND FOR MIGRATE"},
		{"XA PREPARE 'g'", true, "XA PREPARE 'g'"},
		{"XA COMMIT 'g'", true, "XA COMMIT 'g'"},
		{"XA COMMIT 'g' ONE PHASE", true, "XA COMMIT 'g' ONE PHASE"},
		{"XA ROLLBACK 'g'", true, "XA ROLLBACK 'g'"},
		{"XA RECOVER", true, "XA RECOVER"},
		{"XA RECOVER CONVERT XID", true, "XA RECOVER CONVERT XID"},
		{"XA START", false, ""},
	}
	RunTest(t, table, false)
}

func TestSpatialReferenceSystem(t *testing.T) {
	table := []testCase{
		{`CREATE SPATIAL REFERENCE SYSTEM 4120 NAME 'Bessel' DEFINITION 'GEOGCS[]'`, true, "CREATE SPATIAL REFERENCE SYSTEM 4120 NAME 'Bessel' DEFINITION 'GEOGCS[]'"},
		{`CREATE OR REPLACE SPATIAL REFERENCE SYSTEM 4120 ORGANIZATION 'EPSG' IDENTIFIED BY 4120 DESCRIPTION 'd' NAME 'n' DEFINITION 'def'`, true, "CREATE OR REPLACE SPATIAL REFERENCE SYSTEM 4120 ORGANIZATION 'EPSG' IDENTIFIED BY 4120 DESCRIPTION 'd' NAME 'n' DEFINITION 'def'"},
		{`CREATE SPATIAL REFERENCE SYSTEM IF NOT EXISTS 4120 NAME 'n' DEFINITION 'def'`, true, "CREATE SPATIAL REFERENCE SYSTEM IF NOT EXISTS 4120 NAME 'n' DEFINITION 'def'"},
		{"DROP SPATIAL REFERENCE SYSTEM 4120", true, "DROP SPATIAL REFERENCE SYSTEM 4120"},
		{"DROP SPATIAL REFERENCE SYSTEM IF EXISTS 4120", true, "DROP SPATIAL REFERENCE SYSTEM IF EXISTS 4120"},
		// unrelated statements starting with the same tokens still parse
		{"CREATE SPATIAL INDEX idx ON t (g)", true, "CREATE SPATIAL INDEX `idx` ON `t` (`g`)"},
	}
	RunTest(t, table, false)
}

func TestTablespaceDDL(t *testing.T) {
	table := []testCase{
		{"CREATE TABLESPACE ts1 ADD DATAFILE 'ts1.ibd'", true, "CREATE TABLESPACE `ts1` ADD DATAFILE 'ts1.ibd'"},
		{"CREATE TABLESPACE ts1", true, "CREATE TABLESPACE `ts1`"},
		{"CREATE TABLESPACE ts1 ADD DATAFILE 'f' ENGINE = InnoDB", true, "CREATE TABLESPACE `ts1` ADD DATAFILE 'f' ENGINE = `InnoDB`"},
		{"CREATE TABLESPACE ts1 ADD DATAFILE 'f' FILE_BLOCK_SIZE = 8192 ENCRYPTION = 'Y'", true, "CREATE TABLESPACE `ts1` ADD DATAFILE 'f' FILE_BLOCK_SIZE = 8192 ENCRYPTION = 'Y'"},
		{"CREATE TABLESPACE ts1 ADD DATAFILE 'f' USE LOGFILE GROUP lg1 EXTENT_SIZE 4M INITIAL_SIZE 12M ENGINE NDB", true, "CREATE TABLESPACE `ts1` ADD DATAFILE 'f' USE LOGFILE GROUP `lg1` EXTENT_SIZE = 4M INITIAL_SIZE = 12M ENGINE = `NDB`"},
		{"CREATE UNDO TABLESPACE u1 ADD DATAFILE 'u1.ibu'", true, "CREATE UNDO TABLESPACE `u1` ADD DATAFILE 'u1.ibu'"},
		{"ALTER TABLESPACE ts1 ADD DATAFILE 'f2' INITIAL_SIZE = 1G WAIT", true, "ALTER TABLESPACE `ts1` ADD DATAFILE 'f2' INITIAL_SIZE = 1G WAIT"},
		{"ALTER TABLESPACE ts1 DROP DATAFILE 'f2' ENGINE NDB", true, "ALTER TABLESPACE `ts1` DROP DATAFILE 'f2' ENGINE = `NDB`"},
		{"ALTER TABLESPACE ts1 RENAME TO ts2", true, "ALTER TABLESPACE `ts1` RENAME TO `ts2`"},
		{"ALTER TABLESPACE ts1 AUTOEXTEND_SIZE = 64M", true, "ALTER TABLESPACE `ts1` AUTOEXTEND_SIZE = 64M"},
		{"ALTER UNDO TABLESPACE u1 SET INACTIVE", true, "ALTER UNDO TABLESPACE `u1` SET INACTIVE"},
		{"ALTER UNDO TABLESPACE u1 SET ACTIVE ENGINE = InnoDB", true, "ALTER UNDO TABLESPACE `u1` SET ACTIVE ENGINE = `InnoDB`"},
		{"DROP TABLESPACE ts1", true, "DROP TABLESPACE `ts1`"},
		{"DROP TABLESPACE ts1 ENGINE = NDB", true, "DROP TABLESPACE `ts1` ENGINE = `NDB`"},
		{"DROP UNDO TABLESPACE u1", true, "DROP UNDO TABLESPACE `u1`"},
		{"CREATE LOGFILE GROUP lg1 ADD UNDOFILE 'undo.dat' UNDO_BUFFER_SIZE = 8M ENGINE = NDB", true, "CREATE LOGFILE GROUP `lg1` ADD UNDOFILE 'undo.dat' UNDO_BUFFER_SIZE = 8M ENGINE = `NDB`"},
		{"ALTER LOGFILE GROUP lg1 ADD UNDOFILE 'undo2.dat' INITIAL_SIZE 4M WAIT ENGINE NDB", true, "ALTER LOGFILE GROUP `lg1` ADD UNDOFILE 'undo2.dat' INITIAL_SIZE = 4M WAIT ENGINE = `NDB`"},
		{"DROP LOGFILE GROUP lg1 ENGINE = NDB", true, "DROP LOGFILE GROUP `lg1` ENGINE = `NDB`"},
		{"CREATE TABLESPACE ts1 ADD DATAFILE 'f' INITIAL_SIZE = 12M, MAX_SIZE = 100M, NODEGROUP = 3, NO_WAIT", true, "CREATE TABLESPACE `ts1` ADD DATAFILE 'f' INITIAL_SIZE = 12M MAX_SIZE = 100M NODEGROUP = 3 NO_WAIT"},
	}
	RunTest(t, table, false)
}

func TestAlterInstance(t *testing.T) {
	table := []testCase{
		{"ALTER INSTANCE RELOAD TLS", true, "ALTER INSTANCE RELOAD TLS"},
		{"ALTER INSTANCE RELOAD TLS NO ROLLBACK ON ERROR", true, "ALTER INSTANCE RELOAD TLS NO ROLLBACK ON ERROR"},
		{"ALTER INSTANCE RELOAD TLS FOR CHANNEL mysql_admin", true, "ALTER INSTANCE RELOAD TLS FOR CHANNEL `mysql_admin`"},
		{"ALTER INSTANCE RELOAD TLS FOR CHANNEL mysql_main NO ROLLBACK ON ERROR", true, "ALTER INSTANCE RELOAD TLS FOR CHANNEL `mysql_main` NO ROLLBACK ON ERROR"},
		{"ALTER INSTANCE ROTATE INNODB MASTER KEY", true, "ALTER INSTANCE ROTATE INNODB MASTER KEY"},
		{"ALTER INSTANCE ROTATE BINLOG MASTER KEY", true, "ALTER INSTANCE ROTATE BINLOG MASTER KEY"},
		{"ALTER INSTANCE ROTATE innodb master key", true, "ALTER INSTANCE ROTATE INNODB MASTER KEY"},
		{"ALTER INSTANCE ENABLE INNODB REDO_LOG", true, "ALTER INSTANCE ENABLE INNODB REDO_LOG"},
		{"ALTER INSTANCE DISABLE INNODB REDO_LOG", true, "ALTER INSTANCE DISABLE INNODB REDO_LOG"},
		{"ALTER INSTANCE RELOAD KEYRING", true, "ALTER INSTANCE RELOAD KEYRING"},
		{"ALTER INSTANCE ROTATE FOO MASTER KEY", false, ""},
		{"ALTER INSTANCE ENABLE FOO REDO_LOG", false, ""},
	}
	RunTest(t, table, false)
}

func TestColumnVisibility(t *testing.T) {
	table := []testCase{
		{"CREATE TABLE t (a INT, b INT INVISIBLE)", true, "CREATE TABLE `t` (`a` INT,`b` INT INVISIBLE)"},
		{"CREATE TABLE t (a INT, b INT VISIBLE)", true, "CREATE TABLE `t` (`a` INT,`b` INT VISIBLE)"},
		{"CREATE TABLE t (a INT, b INT INVISIBLE NOT NULL DEFAULT 5)", true, "CREATE TABLE `t` (`a` INT,`b` INT INVISIBLE NOT NULL DEFAULT 5)"},
		// SHOW CREATE TABLE emits the attribute inside a versioned comment.
		{"CREATE TABLE t (a INT, b INT /*!80023 INVISIBLE */ DEFAULT NULL)", true, "CREATE TABLE `t` (`a` INT,`b` INT INVISIBLE DEFAULT NULL)"},
		{"CREATE TABLE t (a INT, b INT GENERATED ALWAYS AS (a + 1) VIRTUAL INVISIBLE)", true, "CREATE TABLE `t` (`a` INT,`b` INT GENERATED ALWAYS AS(`a`+1) VIRTUAL INVISIBLE)"},
		{"CREATE TABLE t (a INT, b INT GENERATED ALWAYS AS (a + 1) STORED INVISIBLE)", true, "CREATE TABLE `t` (`a` INT,`b` INT GENERATED ALWAYS AS(`a`+1) STORED INVISIBLE)"},
		{"ALTER TABLE t1 ADD COLUMN x INT INVISIBLE", true, "ALTER TABLE `t1` ADD COLUMN `x` INT INVISIBLE"},
		{"ALTER TABLE t1 MODIFY a INT INVISIBLE", true, "ALTER TABLE `t1` MODIFY COLUMN `a` INT INVISIBLE"},
		{"ALTER TABLE t1 MODIFY a INT VISIBLE", true, "ALTER TABLE `t1` MODIFY COLUMN `a` INT VISIBLE"},
		{"ALTER TABLE t1 ALTER COLUMN a SET VISIBLE", true, "ALTER TABLE `t1` ALTER COLUMN `a` SET VISIBLE"},
		{"ALTER TABLE t1 ALTER COLUMN a SET INVISIBLE", true, "ALTER TABLE `t1` ALTER COLUMN `a` SET INVISIBLE"},
		{"ALTER TABLE t1 ALTER a SET INVISIBLE", true, "ALTER TABLE `t1` ALTER COLUMN `a` SET INVISIBLE"},
	}
	RunTest(t, table, false)
}

func TestEngineAttribute(t *testing.T) {
	table := []testCase{
		{`CREATE TABLE t (c INT ENGINE_ATTRIBUTE '{"x":1}')`, true, "CREATE TABLE `t` (`c` INT ENGINE_ATTRIBUTE = '{\"x\":1}')"},
		{`CREATE TABLE t (c INT ENGINE_ATTRIBUTE = '{"x":1}' SECONDARY_ENGINE_ATTRIBUTE = '{"y":2}')`, true, "CREATE TABLE `t` (`c` INT ENGINE_ATTRIBUTE = '{\"x\":1}' SECONDARY_ENGINE_ATTRIBUTE = '{\"y\":2}')"},
		{`CREATE TABLE t (a VARCHAR(200), UNIQUE KEY k (a) VISIBLE ENGINE_ATTRIBUTE '{"a":1}')`, true, "CREATE TABLE `t` (`a` VARCHAR(200),UNIQUE `k`(`a`) VISIBLE ENGINE_ATTRIBUTE = '{\"a\":1}')"},
		{`CREATE INDEX i ON t1 ((a + b)) INVISIBLE ENGINE_ATTRIBUTE '{"x":1}'`, true, "CREATE INDEX `i` ON `t1` ((`a`+`b`)) INVISIBLE ENGINE_ATTRIBUTE = '{\"x\":1}'"},
		{`ALTER TABLE t1 ADD INDEX i (a) ENGINE_ATTRIBUTE '{"x":1}'`, true, "ALTER TABLE `t1` ADD INDEX `i`(`a`) ENGINE_ATTRIBUTE = '{\"x\":1}'"},
	}
	RunTest(t, table, false)
}
