// Code generated by goyacc DO NOT EDIT.

// Copyright 2020 PingCAP, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// See the License for the specific language governing permissions and
// limitations under the License.

package parser

import __yyfmt__ "fmt"

import (
	"strconv"

	"github.com/block/spirit/pkg/parser/ast"
)

type yyhintSymType struct {
	yys         int
	offset      int
	ident       string
	number      uint64
	hint        *ast.TableOptimizerHint
	hints       []*ast.TableOptimizerHint
	table       ast.HintTable
	modelIdents []ast.CIStr
}

type yyhintXError struct {
	state, xsym int
}

const (
	yyhintDefault           = 57384
	yyhintEOFCode           = 57344
	yyhintErrCode           = 57345
	hintBKA                 = 57356
	hintBNL                 = 57358
	hintDupsWeedOut         = 57380
	hintFirstMatch          = 57381
	hintHashJoin            = 57360
	hintIdentifier          = 57347
	hintIndexMerge          = 57364
	hintIntLit              = 57346
	hintInvalid             = 57348
	hintJoinFixedOrder      = 57352
	hintJoinOrder           = 57353
	hintJoinPrefix          = 57354
	hintJoinSuffix          = 57355
	hintLooseScan           = 57382
	hintMRR                 = 57366
	hintMaterialization     = 57383
	hintMaxExecutionTime    = 57376
	hintMerge               = 57362
	hintNoBKA               = 57357
	hintNoBNL               = 57359
	hintNoHashJoin          = 57361
	hintNoICP               = 57368
	hintNoIndexMerge        = 57365
	hintNoMRR               = 57367
	hintNoMerge             = 57363
	hintNoOrderIndex        = 57375
	hintNoRangeOptimization = 57369
	hintNoSemijoin          = 57373
	hintNoSkipScan          = 57371
	hintNumericLit          = 57351
	hintOrderIndex          = 57374
	hintQBName              = 57379
	hintResourceGroup       = 57378
	hintSemijoin            = 57372
	hintSetVar              = 57377
	hintSingleAtIdentifier  = 57349
	hintSkipScan            = 57370
	hintStringLit           = 57350

	yyhintMaxDepth = 200
	yyhintTabOfs   = -114
)

var (
	yyhintXLAT = map[int]int{
		41:    0,  // ')' (96x)
		57356: 1,  // hintBKA (86x)
		57358: 2,  // hintBNL (86x)
		57360: 3,  // hintHashJoin (86x)
		57347: 4,  // hintIdentifier (86x)
		57364: 5,  // hintIndexMerge (86x)
		57352: 6,  // hintJoinFixedOrder (86x)
		57353: 7,  // hintJoinOrder (86x)
		57354: 8,  // hintJoinPrefix (86x)
		57355: 9,  // hintJoinSuffix (86x)
		57376: 10, // hintMaxExecutionTime (86x)
		57362: 11, // hintMerge (86x)
		57366: 12, // hintMRR (86x)
		57357: 13, // hintNoBKA (86x)
		57359: 14, // hintNoBNL (86x)
		57361: 15, // hintNoHashJoin (86x)
		57368: 16, // hintNoICP (86x)
		57365: 17, // hintNoIndexMerge (86x)
		57363: 18, // hintNoMerge (86x)
		57367: 19, // hintNoMRR (86x)
		57375: 20, // hintNoOrderIndex (86x)
		57369: 21, // hintNoRangeOptimization (86x)
		57373: 22, // hintNoSemijoin (86x)
		57371: 23, // hintNoSkipScan (86x)
		57374: 24, // hintOrderIndex (86x)
		57379: 25, // hintQBName (86x)
		57378: 26, // hintResourceGroup (86x)
		57372: 27, // hintSemijoin (86x)
		57377: 28, // hintSetVar (86x)
		57370: 29, // hintSkipScan (86x)
		44:    30, // ',' (77x)
		57380: 31, // hintDupsWeedOut (67x)
		57381: 32, // hintFirstMatch (67x)
		57382: 33, // hintLooseScan (67x)
		57383: 34, // hintMaterialization (67x)
		57349: 35, // hintSingleAtIdentifier (48x)
		57346: 36, // hintIntLit (47x)
		46:    37, // '.' (43x)
		40:    38, // '(' (36x)
		61:    39, // '=' (35x)
		57344: 40, // $end (21x)
		57390: 41, // Identifier (16x)
		57397: 42, // QueryBlockOpt (15x)
		57351: 43, // hintNumericLit (4x)
		57387: 44, // HintTable (4x)
		57385: 45, // CommaOpt (3x)
		57388: 46, // HintTableList (3x)
		43:    47, // '+' (2x)
		45:    48, // '-' (2x)
		57386: 49, // HintIndexList (2x)
		57350: 50, // hintStringLit (2x)
		57389: 51, // HintTableListOpt (2x)
		57393: 52, // JoinOrderOptimizerHintName (2x)
		57394: 53, // NullaryHintName (2x)
		57399: 54, // SubqueryOptimizerHintName (2x)
		57402: 55, // SubqueryStrategy (2x)
		57403: 56, // SupportedIndexLevelOptimizerHintName (2x)
		57404: 57, // SupportedTableLevelOptimizerHintName (2x)
		57405: 58, // TableOptimizerHintOpt (2x)
		57406: 59, // UnsupportedIndexLevelOptimizerHintName (2x)
		57407: 60, // UnsupportedTableLevelOptimizerHintName (2x)
		57408: 61, // Value (2x)
		57409: 62, // ViewName (2x)
		57391: 63, // IndexNameList (1x)
		57392: 64, // IndexNameListOpt (1x)
		57395: 65, // OptimizerHintList (1x)
		57396: 66, // PartitionList (1x)
		57398: 67, // Start (1x)
		57400: 68, // SubqueryStrategies (1x)
		57401: 69, // SubqueryStrategiesOpt (1x)
		57410: 70, // ViewNameList (1x)
		57384: 71, // $default (0x)
		57345: 72, // error (0x)
		57348: 73, // hintInvalid (0x)
	}

	yyhintSymNames = []string{
		"')'",
		"hintBKA",
		"hintBNL",
		"hintHashJoin",
		"hintIdentifier",
		"hintIndexMerge",
		"hintJoinFixedOrder",
		"hintJoinOrder",
		"hintJoinPrefix",
		"hintJoinSuffix",
		"hintMaxExecutionTime",
		"hintMerge",
		"hintMRR",
		"hintNoBKA",
		"hintNoBNL",
		"hintNoHashJoin",
		"hintNoICP",
		"hintNoIndexMerge",
		"hintNoMerge",
		"hintNoMRR",
		"hintNoOrderIndex",
		"hintNoRangeOptimization",
		"hintNoSemijoin",
		"hintNoSkipScan",
		"hintOrderIndex",
		"hintQBName",
		"hintResourceGroup",
		"hintSemijoin",
		"hintSetVar",
		"hintSkipScan",
		"','",
		"hintDupsWeedOut",
		"hintFirstMatch",
		"hintLooseScan",
		"hintMaterialization",
		"hintSingleAtIdentifier",
		"hintIntLit",
		"'.'",
		"'('",
		"'='",
		"$end",
		"Identifier",
		"QueryBlockOpt",
		"hintNumericLit",
		"HintTable",
		"CommaOpt",
		"HintTableList",
		"'+'",
		"'-'",
		"HintIndexList",
		"hintStringLit",
		"HintTableListOpt",
		"JoinOrderOptimizerHintName",
		"NullaryHintName",
		"SubqueryOptimizerHintName",
		"SubqueryStrategy",
		"SupportedIndexLevelOptimizerHintName",
		"SupportedTableLevelOptimizerHintName",
		"TableOptimizerHintOpt",
		"UnsupportedIndexLevelOptimizerHintName",
		"UnsupportedTableLevelOptimizerHintName",
		"Value",
		"ViewName",
		"IndexNameList",
		"IndexNameListOpt",
		"OptimizerHintList",
		"PartitionList",
		"Start",
		"SubqueryStrategies",
		"SubqueryStrategiesOpt",
		"ViewNameList",
		"$default",
		"error",
		"hintInvalid",
	}

	yyhintReductions = []struct{ xsym, components int }{
		{0, 1},
		{67, 1},
		{65, 1},
		{65, 3},
		{58, 4},
		{58, 4},
		{58, 4},
		{58, 4},
		{58, 4},
		{58, 4},
		{58, 5},
		{58, 5},
		{58, 6},
		{58, 4},
		{58, 4},
		{58, 6},
		{58, 4},
		{58, 5},
		{58, 4},
		{58, 6},
		{58, 6},
		{42, 0},
		{42, 1},
		{45, 0},
		{45, 1},
		{66, 1},
		{66, 3},
		{51, 1},
		{51, 1},
		{46, 2},
		{46, 3},
		{44, 2},
		{44, 4},
		{70, 3},
		{70, 1},
		{62, 2},
		{62, 1},
		{49, 4},
		{64, 0},
		{64, 1},
		{63, 1},
		{63, 3},
		{69, 0},
		{69, 1},
		{68, 1},
		{68, 3},
		{61, 1},
		{61, 1},
		{61, 1},
		{61, 1},
		{61, 2},
		{61, 2},
		{61, 2},
		{61, 2},
		{52, 1},
		{52, 1},
		{52, 1},
		{60, 1},
		{60, 1},
		{60, 1},
		{60, 1},
		{60, 1},
		{57, 1},
		{57, 1},
		{57, 1},
		{59, 1},
		{59, 1},
		{59, 1},
		{59, 1},
		{59, 1},
		{59, 1},
		{59, 1},
		{56, 1},
		{56, 1},
		{54, 1},
		{54, 1},
		{55, 1},
		{55, 1},
		{55, 1},
		{55, 1},
		{53, 1},
		{41, 1},
		{41, 1},
		{41, 1},
		{41, 1},
		{41, 1},
		{41, 1},
		{41, 1},
		{41, 1},
		{41, 1},
		{41, 1},
		{41, 1},
		{41, 1},
		{41, 1},
		{41, 1},
		{41, 1},
		{41, 1},
		{41, 1},
		{41, 1},
		{41, 1},
		{41, 1},
		{41, 1},
		{41, 1},
		{41, 1},
		{41, 1},
		{41, 1},
		{41, 1},
		{41, 1},
		{41, 1},
		{41, 1},
		{41, 1},
		{41, 1},
		{41, 1},
		{41, 1},
	}

	yyhintXErrors = map[yyhintXError]string{}

	yyhintParseTab = [177][]uint16{
		// 0
		{1: 134, 136, 140, 130, 142, 118, 131, 132, 133, 125, 139, 143, 135, 137, 141, 145, 153, 138, 144, 150, 146, 152, 148, 149, 128, 127, 151, 126, 147, 52: 119, 129, 124, 56: 123, 121, 117, 122, 120, 65: 116, 67: 115},
		{40: 114},
		{1: 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 207, 40: 113, 45: 289},
		{1: 112, 112, 112, 112, 112, 112, 112, 112, 112, 112, 112, 112, 112, 112, 112, 112, 112, 112, 112, 112, 112, 112, 112, 112, 112, 112, 112, 112, 112, 112, 40: 112},
		{38: 286},
		// 5
		{38: 282},
		{38: 279},
		{38: 271},
		{38: 268},
		{38: 252},
		// 10
		{38: 240},
		{38: 236},
		{38: 231},
		{38: 228},
		{38: 216},
		// 15
		{38: 213},
		{38: 154},
		{38: 60},
		{38: 59},
		{38: 58},
		// 20
		{38: 57},
		{38: 56},
		{38: 55},
		{38: 54},
		{38: 53},
		// 25
		{38: 52},
		{38: 51},
		{38: 50},
		{38: 49},
		{38: 48},
		// 30
		{38: 47},
		{38: 46},
		{38: 45},
		{38: 44},
		{38: 43},
		// 35
		{38: 42},
		{38: 41},
		{38: 40},
		{38: 39},
		{38: 34},
		// 40
		{1: 164, 166, 168, 159, 172, 160, 161, 162, 163, 184, 170, 174, 165, 167, 169, 176, 173, 171, 175, 183, 177, 181, 179, 182, 187, 186, 180, 185, 178, 31: 188, 189, 190, 191, 158, 93, 41: 157, 155, 66: 156},
		{36: 211},
		{205, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 207, 91, 91, 91, 91, 36: 91, 45: 206},
		{89, 89, 89, 89, 89, 89, 89, 89, 89, 89, 89, 89, 89, 89, 89, 89, 89, 89, 89, 89, 89, 89, 89, 89, 89, 89, 89, 89, 89, 89, 89, 89, 89, 89, 89, 36: 89, 39: 192},
		{92, 92, 92, 92, 92, 92, 92, 92, 92, 92, 92, 92, 92, 92, 92, 92, 92, 92, 92, 92, 92, 92, 92, 92, 92, 92, 92, 92, 92, 92, 92, 92, 92, 92, 92, 36: 92, 92},
		// 45
		{33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 39: 33},
		{32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 39: 32},
		{31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 39: 31},
		{30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 39: 30},
		{29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 39: 29},
		// 50
		{28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 39: 28},
		{27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 39: 27},
		{26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 39: 26},
		{25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 39: 25},
		{24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 39: 24},
		// 55
		{23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 39: 23},
		{22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 39: 22},
		{21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 39: 21},
		{20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 39: 20},
		{19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 39: 19},
		// 60
		{18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 39: 18},
		{17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 39: 17},
		{16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 39: 16},
		{15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 39: 15},
		{14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 39: 14},
		// 65
		{13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 39: 13},
		{12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 39: 12},
		{11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 39: 11},
		{10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 39: 10},
		{9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 39: 9},
		// 70
		{8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 39: 8},
		{7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 39: 7},
		{6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 39: 6},
		{5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 39: 5},
		{4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 39: 4},
		// 75
		{3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 39: 3},
		{2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 39: 2},
		{1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 39: 1},
		{1: 164, 166, 168, 159, 172, 160, 161, 162, 163, 184, 170, 174, 165, 167, 169, 176, 173, 171, 175, 183, 177, 181, 179, 182, 187, 186, 180, 185, 178, 31: 188, 189, 190, 191, 36: 197, 41: 195, 43: 196, 47: 198, 199, 50: 194, 61: 193},
		{204},
		// 80
		{68},
		{67},
		{66},
		{65},
		{36: 203, 43: 202},
		// 85
		{36: 201, 43: 200},
		{63},
		{61},
		{64},
		{62},
		// 90
		{1: 94, 94, 94, 94, 94, 94, 94, 94, 94, 94, 94, 94, 94, 94, 94, 94, 94, 94, 94, 94, 94, 94, 94, 94, 94, 94, 94, 94, 94, 94, 40: 94},
		{1: 96, 96, 96, 96, 96, 96, 96, 96, 96, 96, 96, 96, 96, 96, 96, 96, 96, 96, 96, 96, 96, 96, 96, 96, 96, 96, 96, 96, 96, 96, 40: 96},
		{1: 164, 166, 168, 159, 172, 160, 161, 162, 163, 184, 170, 174, 165, 167, 169, 176, 173, 171, 175, 183, 177, 181, 179, 182, 187, 186, 180, 185, 178, 31: 188, 189, 190, 191, 36: 208, 41: 209},
		{90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 31: 90, 90, 90, 90, 36: 90},
		{210},
		// 95
		{88, 88, 88, 88, 88, 88, 88, 88, 88, 88, 88, 88, 88, 88, 88, 88, 88, 88, 88, 88, 88, 88, 88, 88, 88, 88, 88, 88, 88, 88, 88, 88, 88, 88, 88, 36: 88},
		{1: 95, 95, 95, 95, 95, 95, 95, 95, 95, 95, 95, 95, 95, 95, 95, 95, 95, 95, 95, 95, 95, 95, 95, 95, 95, 95, 95, 95, 95, 95, 40: 95},
		{212},
		{1: 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 40: 97},
		{93, 35: 158, 42: 214},
		// 100
		{215},
		{1: 98, 98, 98, 98, 98, 98, 98, 98, 98, 98, 98, 98, 98, 98, 98, 98, 98, 98, 98, 98, 98, 98, 98, 98, 98, 98, 98, 98, 98, 98, 40: 98},
		{1: 164, 166, 168, 159, 172, 160, 161, 162, 163, 184, 170, 174, 165, 167, 169, 176, 173, 171, 175, 183, 177, 181, 179, 182, 187, 186, 180, 185, 178, 31: 188, 189, 190, 191, 41: 217},
		{218, 30: 219},
		{1: 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 40: 100},
		// 105
		{93, 164, 166, 168, 159, 172, 160, 161, 162, 163, 184, 170, 174, 165, 167, 169, 176, 173, 171, 175, 183, 177, 181, 179, 182, 187, 186, 180, 185, 178, 31: 188, 189, 190, 191, 158, 37: 93, 41: 222, 223, 62: 221, 70: 220},
		{225, 37: 226},
		{80, 37: 80},
		{93, 35: 158, 37: 93, 42: 224},
		{78, 37: 78},
		// 110
		{79, 37: 79},
		{1: 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 40: 99},
		{93, 164, 166, 168, 159, 172, 160, 161, 162, 163, 184, 170, 174, 165, 167, 169, 176, 173, 171, 175, 183, 177, 181, 179, 182, 187, 186, 180, 185, 178, 31: 188, 189, 190, 191, 158, 37: 93, 41: 222, 223, 62: 227},
		{81, 37: 81},
		{1: 164, 166, 168, 159, 172, 160, 161, 162, 163, 184, 170, 174, 165, 167, 169, 176, 173, 171, 175, 183, 177, 181, 179, 182, 187, 186, 180, 185, 178, 31: 188, 189, 190, 191, 41: 229},
		// 115
		{230},
		{1: 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 40: 101},
		{1: 164, 166, 168, 159, 172, 160, 161, 162, 163, 184, 170, 174, 165, 167, 169, 176, 173, 171, 175, 183, 177, 181, 179, 182, 187, 186, 180, 185, 178, 31: 188, 189, 190, 191, 41: 232},
		{39: 233},
		{1: 164, 166, 168, 159, 172, 160, 161, 162, 163, 184, 170, 174, 165, 167, 169, 176, 173, 171, 175, 183, 177, 181, 179, 182, 187, 186, 180, 185, 178, 31: 188, 189, 190, 191, 36: 197, 41: 195, 43: 196, 47: 198, 199, 50: 194, 61: 234},
		// 120
		{235},
		{1: 102, 102, 102, 102, 102, 102, 102, 102, 102, 102, 102, 102, 102, 102, 102, 102, 102, 102, 102, 102, 102, 102, 102, 102, 102, 102, 102, 102, 102, 102, 40: 102},
		{35: 158, 93, 42: 237},
		{36: 238},
		{239},
		// 125
		{1: 103, 103, 103, 103, 103, 103, 103, 103, 103, 103, 103, 103, 103, 103, 103, 103, 103, 103, 103, 103, 103, 103, 103, 103, 103, 103, 103, 103, 103, 103, 40: 103},
		{93, 31: 93, 93, 93, 93, 158, 42: 241},
		{72, 31: 245, 246, 247, 248, 55: 244, 68: 243, 242},
		{251},
		{71, 30: 249},
		// 130
		{70, 30: 70},
		{38, 30: 38},
		{37, 30: 37},
		{36, 30: 36},
		{35, 30: 35},
		// 135
		{31: 245, 246, 247, 248, 55: 250},
		{69, 30: 69},
		{1: 104, 104, 104, 104, 104, 104, 104, 104, 104, 104, 104, 104, 104, 104, 104, 104, 104, 104, 104, 104, 104, 104, 104, 104, 104, 104, 104, 104, 104, 104, 40: 104},
		{1: 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 31: 93, 93, 93, 93, 158, 42: 254, 49: 253},
		{267},
		// 140
		{1: 164, 166, 168, 159, 172, 160, 161, 162, 163, 184, 170, 174, 165, 167, 169, 176, 173, 171, 175, 183, 177, 181, 179, 182, 187, 186, 180, 185, 178, 31: 188, 189, 190, 191, 41: 255, 44: 256},
		{93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 158, 37: 264, 42: 263},
		{91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 207, 91, 91, 91, 91, 45: 257},
		{76, 164, 166, 168, 159, 172, 160, 161, 162, 163, 184, 170, 174, 165, 167, 169, 176, 173, 171, 175, 183, 177, 181, 179, 182, 187, 186, 180, 185, 178, 31: 188, 189, 190, 191, 41: 260, 63: 259, 258},
		{77},
		// 145
		{75, 30: 261},
		{74, 30: 74},
		{1: 164, 166, 168, 159, 172, 160, 161, 162, 163, 184, 170, 174, 165, 167, 169, 176, 173, 171, 175, 183, 177, 181, 179, 182, 187, 186, 180, 185, 178, 31: 188, 189, 190, 191, 41: 262},
		{73, 30: 73},
		{83, 83, 83, 83, 83, 83, 83, 83, 83, 83, 83, 83, 83, 83, 83, 83, 83, 83, 83, 83, 83, 83, 83, 83, 83, 83, 83, 83, 83, 83, 83, 83, 83, 83, 83},
		// 150
		{1: 164, 166, 168, 159, 172, 160, 161, 162, 163, 184, 170, 174, 165, 167, 169, 176, 173, 171, 175, 183, 177, 181, 179, 182, 187, 186, 180, 185, 178, 31: 188, 189, 190, 191, 41: 265},
		{93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 158, 42: 266},
		{82, 82, 82, 82, 82, 82, 82, 82, 82, 82, 82, 82, 82, 82, 82, 82, 82, 82, 82, 82, 82, 82, 82, 82, 82, 82, 82, 82, 82, 82, 82, 82, 82, 82, 82},
		{1: 105, 105, 105, 105, 105, 105, 105, 105, 105, 105, 105, 105, 105, 105, 105, 105, 105, 105, 105, 105, 105, 105, 105, 105, 105, 105, 105, 105, 105, 105, 40: 105},
		{1: 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 31: 93, 93, 93, 93, 158, 42: 254, 49: 269},
		// 155
		{270},
		{1: 106, 106, 106, 106, 106, 106, 106, 106, 106, 106, 106, 106, 106, 106, 106, 106, 106, 106, 106, 106, 106, 106, 106, 106, 106, 106, 106, 106, 106, 106, 40: 106},
		{93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 31: 93, 93, 93, 93, 158, 42: 274, 46: 273, 51: 272},
		{278},
		{87, 30: 276},
		// 160
		{86, 164, 166, 168, 159, 172, 160, 161, 162, 163, 184, 170, 174, 165, 167, 169, 176, 173, 171, 175, 183, 177, 181, 179, 182, 187, 186, 180, 185, 178, 31: 188, 189, 190, 191, 41: 255, 44: 275},
		{85, 30: 85},
		{1: 164, 166, 168, 159, 172, 160, 161, 162, 163, 184, 170, 174, 165, 167, 169, 176, 173, 171, 175, 183, 177, 181, 179, 182, 187, 186, 180, 185, 178, 31: 188, 189, 190, 191, 41: 255, 44: 277},
		{84, 30: 84},
		{1: 107, 107, 107, 107, 107, 107, 107, 107, 107, 107, 107, 107, 107, 107, 107, 107, 107, 107, 107, 107, 107, 107, 107, 107, 107, 107, 107, 107, 107, 107, 40: 107},
		// 165
		{93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 31: 93, 93, 93, 93, 158, 42: 274, 46: 273, 51: 280},
		{281},
		{1: 108, 108, 108, 108, 108, 108, 108, 108, 108, 108, 108, 108, 108, 108, 108, 108, 108, 108, 108, 108, 108, 108, 108, 108, 108, 108, 108, 108, 108, 108, 40: 108},
		{1: 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 31: 93, 93, 93, 93, 158, 42: 284, 46: 283},
		{285, 30: 276},
		// 170
		{1: 164, 166, 168, 159, 172, 160, 161, 162, 163, 184, 170, 174, 165, 167, 169, 176, 173, 171, 175, 183, 177, 181, 179, 182, 187, 186, 180, 185, 178, 31: 188, 189, 190, 191, 41: 255, 44: 275},
		{1: 109, 109, 109, 109, 109, 109, 109, 109, 109, 109, 109, 109, 109, 109, 109, 109, 109, 109, 109, 109, 109, 109, 109, 109, 109, 109, 109, 109, 109, 109, 40: 109},
		{93, 35: 158, 42: 287},
		{288},
		{1: 110, 110, 110, 110, 110, 110, 110, 110, 110, 110, 110, 110, 110, 110, 110, 110, 110, 110, 110, 110, 110, 110, 110, 110, 110, 110, 110, 110, 110, 110, 40: 110},
		// 175
		{1: 134, 136, 140, 130, 142, 118, 131, 132, 133, 125, 139, 143, 135, 137, 141, 145, 153, 138, 144, 150, 146, 152, 148, 149, 128, 127, 151, 126, 147, 52: 119, 129, 124, 56: 123, 121, 290, 122, 120},
		{1: 111, 111, 111, 111, 111, 111, 111, 111, 111, 111, 111, 111, 111, 111, 111, 111, 111, 111, 111, 111, 111, 111, 111, 111, 111, 111, 111, 111, 111, 111, 40: 111},
	}
)

var yyhintDebug = 0

type yyhintLexer interface {
	Lex(lval *yyhintSymType) int
	Errorf(format string, a ...interface{}) error
	AppendError(err error)
	AppendWarn(err error)
	Errors() (warns []error, errs []error)
}

type yyhintLexerEx interface {
	yyhintLexer
	Reduced(rule, state int, lval *yyhintSymType) bool
}

func yyhintSymName(c int) (s string) {
	x, ok := yyhintXLAT[c]
	if ok {
		return yyhintSymNames[x]
	}

	return __yyfmt__.Sprintf("%d", c)
}

func yyhintlex1(yylex yyhintLexer, lval *yyhintSymType) (n int) {
	n = yylex.Lex(lval)
	if n <= 0 {
		n = yyhintEOFCode
	}
	if yyhintDebug >= 3 {
		__yyfmt__.Printf("\nlex %s(%#x %d), lval: %+v\n", yyhintSymName(n), n, n, lval)
	}
	return n
}

func yyhintParse(yylex yyhintLexer, parser *hintParser) int {
	const yyError = 72

	yyEx, _ := yylex.(yyhintLexerEx)
	var yyn int
	parser.yylval = yyhintSymType{}
	yyS := parser.cache

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yyerrok := func() {
		if yyhintDebug >= 2 {
			__yyfmt__.Printf("yyerrok()\n")
		}
		Errflag = 0
	}
	_ = yyerrok
	yystate := 0
	yychar := -1
	var yyxchar int
	var yyshift int
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	yyp++
	if yyp+1 >= len(yyS) {
		nyys := make([]yyhintSymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
		parser.cache = yyS
	}
	parser.yyVAL = &yyS[yyp+1]
	yyS[yyp].yys = yystate

yynewstate:
	if yychar < 0 {
		yychar = yyhintlex1(yylex, &parser.yylval)
		var ok bool
		if yyxchar, ok = yyhintXLAT[yychar]; !ok {
			yyxchar = len(yyhintSymNames) // > tab width
		}
	}
	if yyhintDebug >= 4 {
		var a []int
		for _, v := range yyS[:yyp+1] {
			a = append(a, v.yys)
		}
		__yyfmt__.Printf("state stack %v\n", a)
	}
	row := yyhintParseTab[yystate]
	yyn = 0
	if yyxchar < len(row) {
		if yyn = int(row[yyxchar]); yyn != 0 {
			yyn += yyhintTabOfs
		}
	}
	switch {
	case yyn > 0: // shift
		yychar = -1
		*parser.yyVAL = parser.yylval
		yystate = yyn
		yyshift = yyn
		if yyhintDebug >= 2 {
			__yyfmt__.Printf("shift, and goto state %d\n", yystate)
		}
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	case yyn < 0: // reduce
	case yystate == 1: // accept
		if yyhintDebug >= 2 {
			__yyfmt__.Println("accept")
		}
		goto ret0
	}

	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			if yyhintDebug >= 1 {
				__yyfmt__.Printf("no action for %s in state %d\n", yyhintSymName(yychar), yystate)
			}
			msg, ok := yyhintXErrors[yyhintXError{yystate, yyxchar}]
			if !ok {
				msg, ok = yyhintXErrors[yyhintXError{yystate, -1}]
			}
			if !ok && yyshift != 0 {
				msg, ok = yyhintXErrors[yyhintXError{yyshift, yyxchar}]
			}
			if !ok {
				msg, ok = yyhintXErrors[yyhintXError{yyshift, -1}]
			}
			if !ok || msg == "" {
				msg = "syntax error"
			}
			// ignore goyacc error message
			yylex.AppendError(yylex.Errorf(""))
			Nerrs++
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				row := yyhintParseTab[yyS[yyp].yys]
				if yyError < len(row) {
					yyn = int(row[yyError]) + yyhintTabOfs
					if yyn > 0 { // hit
						if yyhintDebug >= 2 {
							__yyfmt__.Printf("error recovery found error shift in state %d\n", yyS[yyp].yys)
						}
						yystate = yyn /* simulate a shift of "error" */
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyhintDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			if yyhintDebug >= 2 {
				__yyfmt__.Printf("error recovery failed\n")
			}
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyhintDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyhintSymName(yychar))
			}
			if yychar == yyhintEOFCode {
				goto ret1
			}

			yychar = -1
			goto yynewstate /* try again in the same state */
		}
	}

	r := -yyn
	x0 := yyhintReductions[r]
	x, n := x0.xsym, x0.components
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= n
	if yyp+1 >= len(yyS) {
		nyys := make([]yyhintSymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
		parser.cache = yyS
	}
	parser.yyVAL = &yyS[yyp+1]

	/* consult goto table to find next state */
	exState := yystate
	yystate = int(yyhintParseTab[yyS[yyp].yys][x]) + yyhintTabOfs
	/* reduction by production r */
	if yyhintDebug >= 2 {
		__yyfmt__.Printf("reduce using rule %v (%s), and goto state %d\n", r, yyhintSymNames[x], yystate)
	}

	switch r {
	case 1:
		{
			parser.result = yyS[yypt-0].hints
		}
	case 2:
		{
			if yyS[yypt-0].hint != nil {
				parser.yyVAL.hints = []*ast.TableOptimizerHint{yyS[yypt-0].hint}
			}
		}
	case 3:
		{
			if yyS[yypt-0].hint != nil {
				parser.yyVAL.hints = append(yyS[yypt-2].hints, yyS[yypt-0].hint)
			} else {
				parser.yyVAL.hints = yyS[yypt-2].hints
			}
		}
	case 4:
		{
			parser.warnUnsupportedHint(yyS[yypt-3].ident)
			parser.yyVAL.hint = nil
		}
	case 5:
		{
			parser.warnUnsupportedHint(yyS[yypt-3].ident)
			parser.yyVAL.hint = nil
		}
	case 6:
		{
			parser.warnUnsupportedHint(yyS[yypt-3].ident)
			parser.yyVAL.hint = nil
		}
	case 7:
		{
			h := yyS[yypt-1].hint
			h.HintName = ast.NewCIStr(yyS[yypt-3].ident)
			parser.yyVAL.hint = h
		}
	case 8:
		{
			parser.warnUnsupportedHint(yyS[yypt-3].ident)
			parser.yyVAL.hint = nil
		}
	case 9:
		{
			h := yyS[yypt-1].hint
			h.HintName = ast.NewCIStr(yyS[yypt-3].ident)
			parser.yyVAL.hint = h
		}
	case 10:
		{
			parser.warnUnsupportedHint(yyS[yypt-4].ident)
			parser.yyVAL.hint = nil
		}
	case 11:
		{
			parser.yyVAL.hint = &ast.TableOptimizerHint{
				HintName: ast.NewCIStr(yyS[yypt-4].ident),
				QBName:   ast.NewCIStr(yyS[yypt-2].ident),
				HintData: yyS[yypt-1].number,
			}
		}
	case 12:
		{
			parser.yyVAL.hint = &ast.TableOptimizerHint{
				HintName: ast.NewCIStr(yyS[yypt-5].ident),
				HintData: ast.HintSetVar{
					VarName: yyS[yypt-3].ident,
					Value:   yyS[yypt-1].ident,
				},
			}
		}
	case 13:
		{
			parser.yyVAL.hint = &ast.TableOptimizerHint{
				HintName: ast.NewCIStr(yyS[yypt-3].ident),
				HintData: yyS[yypt-1].ident,
			}
		}
	case 14:
		{
			parser.yyVAL.hint = &ast.TableOptimizerHint{
				HintName: ast.NewCIStr(yyS[yypt-3].ident),
				QBName:   ast.NewCIStr(yyS[yypt-1].ident),
			}
		}
	case 15:
		{
			parser.yyVAL.hint = &ast.TableOptimizerHint{
				HintName: ast.NewCIStr(yyS[yypt-5].ident),
				QBName:   ast.NewCIStr(yyS[yypt-3].ident),
				Tables:   yyS[yypt-1].hint.Tables,
			}
		}
	case 16:
		{
			parser.yyVAL.hint = &ast.TableOptimizerHint{
				HintName: ast.NewCIStr(yyS[yypt-3].ident),
				QBName:   ast.NewCIStr(yyS[yypt-1].ident),
			}
		}
	case 17:
		{
			parser.warnUnsupportedHint(yyS[yypt-4].ident)
			parser.yyVAL.hint = nil
		}
	case 18:
		{
			parser.warnUnsupportedHint(yyS[yypt-3].ident)
			parser.yyVAL.hint = nil
		}
	case 19:
		{
			parser.warnUnsupportedHint(yyS[yypt-5].ident)
			parser.yyVAL.hint = nil
		}
	case 20:
		{
			parser.warnUnsupportedHint(yyS[yypt-5].ident)
			parser.yyVAL.hint = nil
		}
	case 21:
		{
			parser.yyVAL.ident = ""
		}
	case 25:
		{
			parser.yyVAL.modelIdents = []ast.CIStr{ast.NewCIStr(yyS[yypt-0].ident)}
		}
	case 26:
		{
			parser.yyVAL.modelIdents = append(yyS[yypt-2].modelIdents, ast.NewCIStr(yyS[yypt-0].ident))
		}
	case 28:
		{
			parser.yyVAL.hint = &ast.TableOptimizerHint{
				QBName: ast.NewCIStr(yyS[yypt-0].ident),
			}
		}
	case 29:
		{
			parser.yyVAL.hint = &ast.TableOptimizerHint{
				Tables: []ast.HintTable{yyS[yypt-0].table},
				QBName: ast.NewCIStr(yyS[yypt-1].ident),
			}
		}
	case 30:
		{
			h := yyS[yypt-2].hint
			h.Tables = append(h.Tables, yyS[yypt-0].table)
			parser.yyVAL.hint = h
		}
	case 31:
		{
			parser.yyVAL.table = ast.HintTable{
				TableName: ast.NewCIStr(yyS[yypt-1].ident),
				QBName:    ast.NewCIStr(yyS[yypt-0].ident),
			}
		}
	case 32:
		{
			parser.yyVAL.table = ast.HintTable{
				DBName:    ast.NewCIStr(yyS[yypt-3].ident),
				TableName: ast.NewCIStr(yyS[yypt-1].ident),
				QBName:    ast.NewCIStr(yyS[yypt-0].ident),
			}
		}
	case 33:
		{
			h := yyS[yypt-2].hint
			h.Tables = append(h.Tables, yyS[yypt-0].table)
			parser.yyVAL.hint = h
		}
	case 34:
		{
			parser.yyVAL.hint = &ast.TableOptimizerHint{
				Tables: []ast.HintTable{yyS[yypt-0].table},
			}
		}
	case 35:
		{
			parser.yyVAL.table = ast.HintTable{
				TableName: ast.NewCIStr(yyS[yypt-1].ident),
				QBName:    ast.NewCIStr(yyS[yypt-0].ident),
			}
		}
	case 36:
		{
			parser.yyVAL.table = ast.HintTable{
				QBName: ast.NewCIStr(yyS[yypt-0].ident),
			}
		}
	case 37:
		{
			h := yyS[yypt-0].hint
			h.Tables = []ast.HintTable{yyS[yypt-2].table}
			h.QBName = ast.NewCIStr(yyS[yypt-3].ident)
			parser.yyVAL.hint = h
		}
	case 38:
		{
			parser.yyVAL.hint = &ast.TableOptimizerHint{}
		}
	case 40:
		{
			parser.yyVAL.hint = &ast.TableOptimizerHint{
				Indexes: []ast.CIStr{ast.NewCIStr(yyS[yypt-0].ident)},
			}
		}
	case 41:
		{
			h := yyS[yypt-2].hint
			h.Indexes = append(h.Indexes, ast.NewCIStr(yyS[yypt-0].ident))
			parser.yyVAL.hint = h
		}
	case 49:
		{
			parser.yyVAL.ident = strconv.FormatUint(yyS[yypt-0].number, 10)
		}
	case 50:
		{
			parser.yyVAL.ident = yyS[yypt-0].ident
		}
	case 51:
		{
			parser.yyVAL.ident = "-" + yyS[yypt-0].ident
		}
	case 52:
		{
			parser.yyVAL.ident = strconv.FormatUint(yyS[yypt-0].number, 10)
		}
	case 53:
		{
			if yyS[yypt-0].number > 9223372036854775808 {
				yylex.AppendError(yylex.Errorf("the Signed Value should be at the range of [-9223372036854775808, 9223372036854775807]."))
				return 1
			} else if yyS[yypt-0].number == 9223372036854775808 {
				signed_one := int64(1)
				parser.yyVAL.ident = strconv.FormatInt(signed_one<<63, 10)
			} else {
				parser.yyVAL.ident = strconv.FormatInt(-int64(yyS[yypt-0].number), 10)
			}
		}

	}

	if !parser.lexer.skipPositionRecording {
		yyhintSetOffset(parser.yyVAL, parser.yyVAL.offset)
	}

	if yyEx != nil && yyEx.Reduced(r, exState, parser.yyVAL) {
		return -1
	}
	goto yystack /* stack new state and value */
}
